### POST Guide
POST http://localhost:5000/guides
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmNmJmZjMwOGZjZWVmZWJiMWVhYWUyIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzkxMzY1MSwiZXhwIjoxNjk0MDAwMDUxfQ.lU78EXEX1uaOnCSI8Bg3IUoNdHK_Ds7FJgqbSOPWA94

{
  "title": "B Xabar",
  "content": "B Content",
  "notify": true
}

### GET Guide
GET http://localhost:5000/guides
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmNmJmZjMwOGZjZWVmZWJiMWVhYWUyIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzkxMzY1MSwiZXhwIjoxNjk0MDAwMDUxfQ.lU78EXEX1uaOnCSI8Bg3IUoNdHK_Ds7FJgqbSOPWA94
Content-Type: application/json


### GET Guide with { id }
GET http://localhost:5000/guides/64f715f022cdf5d3f2cd4d88
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmNmJmZjMwOGZjZWVmZWJiMWVhYWUyIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzkxMzY1MSwiZXhwIjoxNjk0MDAwMDUxfQ.lU78EXEX1uaOnCSI8Bg3IUoNdHK_Ds7FJgqbSOPWA94
Content-Type: application/json