###
GET http://localhost:5000/user-guides
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmODhhMDQwYWU0N2M5NjM1ZTE5ZjdmIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDAwOTk5OCwiZXhwIjoxNjk0MDk2Mzk4fQ.yG5i4ixNDW7fJL_qC1tsfThfcTMdW9cEYstLKm4Bz88
Content-Type: application/json


###
POST http://localhost:5000/user-guides/64f97217d3e3a99ed7903fd4/read
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmODhhMDQwYWU0N2M5NjM1ZTE5ZjdmIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDAwOTk5OCwiZXhwIjoxNjk0MDk2Mzk4fQ.yG5i4ixNDW7fJL_qC1tsfThfcTMdW9cEYstLKm4Bz88
Content-Type: application/json