### login user
POST http://localhost:5000/users/login
Content-Type: application/json

# {
#   "username": "sherozbek.17",
#   "password": "1234"
# }
{
  "username": "kdeaconson9",
  "password": "1234"
}

### add user
POST http://localhost:5000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json

{
  "first_name": "Nasiba",
  "last_name": "Azimov",
  "role": "employee",
  "age":17,
  "username":"nasiba",
  "password": "1234"
}







### get users without some query
GET http://localhost:5000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json









### get users with GET /users?q=sheroz
GET http://localhost:5000/users?q=sheroz
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json







### get users with GET /users?sort[by]=age&sort[order]=desc
GET http://localhost:5000/users?sort[by]=age&sort[order]=desc
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json







### get users with GET /users?sort[by]=age&sort[order]=desc
GET http://localhost:5000/users?sort[by]=age&sort[order]=asc
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json






### get users with GET /users?filters[role]=employee
GET http://localhost:5000/users?filters[role]=employee
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json









### get users with GET /users?page[offset]=0&page[limit]=10
GET http://localhost:5000/users?page[offset]=0&page[limit]=10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json



### show users
GET http://localhost:5000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
Content-Type: application/json


### edit users with ( id )
PATCH http://localhost:5000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjlkIiwicm9sZSI6ImVtcGxveWVlIn0sImlhdCI6MTY5MzU0ODAzNywiZXhwIjoxNjkzNjM0NDM3fQ.ErHEdpnGMKBzHQrCVtMUwM17AeSIJPHUtmTXhPO3O8M
Content-Type: application/json

{
  "first_name": "Sherozbek",
  "last_name": "nima gap"
}


### remove user with { id }
DELETE http://localhost:5000/users/64ee0dde481fa99395111f94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRlZTBkZGU0ODFmYTk5Mzk1MTExZjk0Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5MzU0MzMzNSwiZXhwIjoxNjkzNjI5NzM1fQ.Mxg8n-yhyiAqsfGaf5HW0dADvimHEipIKAlga3TCr54