const { hashSync } = require("bcryptjs");

const users = [
  {
    first_name: "Sherozbek",
    last_name: "Baxtiyorov",
    role: "admin",
    age: 22,
    username: "sherozbek.17",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Rabi",
    last_name: "Stegers",
    role: "admin",
    age: "11",
    username: "mike",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Adrian",
    last_name: "Readhead",
    role: "admin",
    age: "1079",
    username: "areadhead2",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Tyne",
    last_name: "Murton",
    role: "admin",
    age: "2100",
    username: "tmurton3",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Oralia",
    last_name: "Schoenfisch",
    role: "admin",
    age: "3538",
    username: "oschoenfisch4",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Scarface",
    last_name: "Watt",
    role: "admin",
    age: "56",
    username: "swatt5",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Carlota",
    last_name: "Macer",
    role: "admin",
    age: "127",
    username: "cmacer6",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Melly",
    last_name: "Foulger",
    role: "admin",
    age: "2750",
    username: "mfoulger7",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Dione",
    last_name: "Barttrum",
    role: "admin",
    age: "87",
    username: "dbarttrum8",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Klaus",
    last_name: "Deaconson",
    role: "admin",
    age: "43",
    username: "kdeaconson9",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Ranique",
    last_name: "Bartolomeazzi",
    role: "admin",
    age: "977",
    username: "rbartolomeazzia",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Gabriel",
    last_name: "Spencer",
    role: "employee",
    age: "43",
    username: "gspencerb",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Dionne",
    last_name: "Arnely",
    role: "employee",
    age: "617",
    username: "darnelyc",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Mia",
    last_name: "Hunnicutt",
    role: "employee",
    age: "32",
    username: "mhunnicuttd",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Ludwig",
    last_name: "Lile",
    role: "employee",
    age: "2363",
    username: "llilee",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Mayer",
    last_name: "Brabant",
    role: "employee",
    age: "74",
    username: "mbrabantf",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Ugo",
    last_name: "Hubner",
    role: "employee",
    age: "605",
    username: "uhubnerg",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Joshua",
    last_name: "Simoncelli",
    role: "employee",
    age: "100",
    username: "jsimoncellih",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Dana",
    last_name: "Stiddard",
    role: "employee",
    age: "290",
    username: "dstiddardi",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Mireielle",
    last_name: "Crummie",
    role: "employee",
    age: "276",
    username: "mcrummiej",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Stewart",
    last_name: "Delyth",
    role: "employee",
    age: "531",
    username: "sdelythk",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Pegeen",
    last_name: "Everil",
    role: "employee",
    age: "264",
    username: "peverill",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Corny",
    last_name: "Bygott",
    role: "employee",
    age: "17",
    username: "cbygottm",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Millard",
    last_name: "Yeardsley",
    role: "employee",
    age: "659",
    username: "myeardsleyn",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Agnella",
    last_name: "Wincom",
    role: "employee",
    age: "3600",
    username: "awincomo",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Ezekiel",
    last_name: "Skarr",
    role: "employee",
    age: "10",
    username: "eskarrp",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Prinz",
    last_name: "Wankling",
    role: "employee",
    age: "19",
    username: "pwanklingq",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Sigfrid",
    last_name: "Bourton",
    role: "employee",
    age: "5431",
    username: "sbourtonr",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Sharona",
    last_name: "Brimming",
    role: "employee",
    age: "86",
    username: "sbrimmings",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Caro",
    last_name: "Giraldez",
    role: "employee",
    age: "62",
    username: "cgiraldezt",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Magdalen",
    last_name: "Huston",
    role: "employee",
    age: "3229",
    username: "mhustonu",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Winslow",
    last_name: "Scafe",
    role: "employee",
    age: "5730",
    username: "wscafev",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Rolando",
    last_name: "Evenden",
    role: "employee",
    age: "1442",
    username: "revendenw",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Margarethe",
    last_name: "Poston",
    role: "employee",
    age: "62",
    username: "mpostonx",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Michelina",
    last_name: "Peatheyjohns",
    role: "employee",
    age: "1148",
    username: "mpeatheyjohnsy",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Rici",
    last_name: "Filipovic",
    role: "employee",
    age: "501",
    username: "rfilipovicz",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Almeta",
    last_name: "Southwick",
    role: "employee",
    age: "2430",
    username: "asouthwick10",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Jessey",
    last_name: "Jowitt",
    role: "employee",
    age: "59",
    username: "jjowitt11",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Laurent",
    last_name: "Acome",
    role: "employee",
    age: "5140",
    username: "lacome12",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Gregory",
    last_name: "Pisculli",
    role: "employee",
    age: "55",
    username: "gpisculli13",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Teador",
    last_name: "Pesselt",
    role: "employee",
    age: "1472",
    username: "tpesselt14",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Harmony",
    last_name: "Nussen",
    role: "employee",
    age: "137",
    username: "hnussen15",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Lorin",
    last_name: "Ickovits",
    role: "employee",
    age: "800",
    username: "lickovits16",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Beatrice",
    last_name: "Budge",
    role: "employee",
    age: "1020",
    username: "bbudge17",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Lyndy",
    last_name: "Elias",
    role: "employee",
    age: "452",
    username: "lelias18",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Timofei",
    last_name: "Emons",
    role: "employee",
    age: "325",
    username: "temons19",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Jenna",
    last_name: "Instock",
    role: "employee",
    age: "657",
    username: "jinstock1a",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Jolie",
    last_name: "Scheffler",
    role: "employee",
    age: "2871",
    username: "jscheffler1b",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Ronni",
    last_name: "Gilby",
    role: "employee",
    age: "8",
    username: "rgilby1c",
    password: hashSync("1234", 10),
  },
  {
    first_name: "Haywood",
    last_name: "Colleford",
    role: "employee",
    age: "517",
    username: "hcolleford1d",
    password: hashSync("1234", 10),
  },
];

module.exports = users;
